### ISSUE TITLE
任意内容都搜索不出来

### ISSUE THREAD

**Issue by peipei731** [Nomination-NRB/SearchEngine#1]
安装好依赖的库以及下载好词库并放到指定的位置之后
运行，打开网页，搜索任何的关键字都显示Sorry, no web pages found for your search!
这个问题是什么原因以及该如何解决呢？
![屏幕截图 2024-10-22 205421](https://github.com/user-attachments/assets/836afc77-6965-455b-a6e9-67edc6747135)
![屏幕截图 2024-10-22 204830](https://github.com/user-attachments/assets/3e3da77c-29e3-451e-9536-0cc69abe6914)

**Comment by Nomination-NRB** [comment]
> 安装好依赖的库以及下载好词库并放到指定的位置之后 运行，打开网页，搜索任何的关键字都显示Sorry, no web pages found for your search! 这个问题是什么原因以及该如何解决呢？ ![屏幕截图 2024-10-22 205421](https://private-user-images.githubusercontent.com/185082651/378848051-836afc77-6965-455b-a6e9-67edc6747135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDk5NTcsIm5iZiI6MTcyOTY0OTY1NywicGF0aCI6Ii8xODUwODI2NTEvMzc4ODQ4MDUxLTgzNmFmYzc3LTY5NjUtNDU1Yi1hNmU5LTY3ZWRjNjc0NzEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwMjE0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjFkOTgwY2Y0NWFmNzI3MjMyY2QyMjA0NzA3NzlkMTdkODEzNDlkZDBlYzBmZTE4MjZmNGEwNzY4MWUxNDlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U5vB8kBmblt7alvPl8DPnonxdn3Zcvc0TI1GuHZnsl8) ![屏幕截图 2024-10-22 204830](https://private-user-images.githubusercontent.com/185082651/378848094-3e3da77c-29e3-451e-9536-0cc69abe6914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDk5NTcsIm5iZiI6MTcyOTY0OTY1NywicGF0aCI6Ii8xODUwODI2NTEvMzc4ODQ4MDk0LTNlM2RhNzdjLTI5ZTMtNDUxZS05NTM2LTBjYzY5YWJlNjkxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwMjE0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2Q2ODNjNDE3NzljZDJkM2FmNTBkYWEyMTNlYTc4ZTQzMjMxN2QzZjkwNzBhYjZhMjVlYTY5MmM5ZWZmYzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vdEXd-kLbzOE18bpNAJ0zPSbZFf0MUQHDTLQim87yS8)

我复现了一下，问题出在没有先执行code文件夹下的setup.py，需要先构建索引与推荐阅读模块，运行完成setup.py后再运行main.py即可，最后正常的结果如图：
![image](https://github.com/user-attachments/assets/10933e5d-160b-4c5e-8ef6-26a86a8e0fcb)

**Comment by Nomination-NRB** [comment]
> 安装好依赖的库以及下载好词库并放到指定的位置之后 运行，打开网页，搜索任何的关键字都显示Sorry, no web pages found for your search! 这个问题是什么原因以及该如何解决呢？ ![屏幕截图 2024-10-22 205421](https://private-user-images.githubusercontent.com/185082651/378848051-836afc77-6965-455b-a6e9-67edc6747135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA2NzQsIm5iZiI6MTcyOTY1MDM3NCwicGF0aCI6Ii8xODUwODI2NTEvMzc4ODQ4MDUxLTgzNmFmYzc3LTY5NjUtNDU1Yi1hNmU5LTY3ZWRjNjc0NzEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwMjI2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjY1OWZiMTAxNTlmMWQ3ZWFkYmVlYTgyNGU5Y2RiN2NjMjVlMjE2YWNhODJlNzdjMTlkMmM4ZTFiNzZjNjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zni6KmSf8sZPYYbBJHQqF_eBblNJUMkBGlXyXyKedao) ![屏幕截图 2024-10-22 204830](https://private-user-images.githubusercontent.com/185082651/378848094-3e3da77c-29e3-451e-9536-0cc69abe6914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA2NzQsIm5iZiI6MTcyOTY1MDM3NCwicGF0aCI6Ii8xODUwODI2NTEvMzc4ODQ4MDk0LTNlM2RhNzdjLTI5ZTMtNDUxZS05NTM2LTBjYzY5YWJlNjkxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwMjI2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NThkZjY2YTMwMDk4OWY2NDYyMzNhNWYzYjRiYmE5N2Q2NWJlMjg1YjQ2NzBiMTgyOGRhZmQwMDBhZTQyM2VhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.euKn3ij7q58NmxtX2lGLlX0ZpOGI89J1_usOB8iWgBE)

readme运行说明也同步修正了

**Comment by peipei731** [comment]
可以了可以了😊！感谢大佬的指导
